In [1]:
import sys
import os
import pandas as pd
sys.path.append(os.path.abspath(".."))

from src.data.data_manager import DataManager
from src.data.features_engineering import unique_values, missing_values, duplicates_values

In [2]:
data = DataManager("C:/Users/danil/Desktop/PROJECTS/formula1/datasets/raw/")

### Unique Count from results

In [3]:
results = data.get("results")

unique_df = pd.DataFrame({
    'Category': ['Constructors', 'Drivers', 'Races'],
    'Unique Count': [
        unique_values(results['constructorId']),
        unique_values(results['driverId']),
        unique_values(results['raceId']),
    ]
})
display(unique_df)

       Category  Unique Count
0  Constructors           211
1       Drivers           861
2         Races          1125

### Check missing values from results

In [4]:
categories = ['Constructors', 'Drivers', 'Races']
columns = ['constructorId', 'driverId', 'raceId']
tables = ['constructors', 'drivers', 'races']

missing_df = pd.DataFrame([
    {
        'Category': cat,
        'Missing Values': missing_values(
            results[col],
            data.get(table)[col]
        )
    }
    for cat, col, table in zip(categories, columns, tables)
])
display(missing_df)

       Category Missing Values
0  Constructors             {}
1       Drivers             {}
2         Races             {}

### Check duplicates from results

In [5]:
duplicates_df = pd.DataFrame([
    {
        'Category': cat,
        'Duplicate Count': duplicates_values(data.get(table)[col])
    }
    for cat, col, table in zip(categories, columns, tables)
])
display(duplicates_df)

       Category  Duplicate Count
0  Constructors                0
1       Drivers                0
2         Races                0