In [2]:
import sys
import os

project_root = os.path.abspath("..")
if project_root not in sys.path:
    sys.path.append(project_root)

from src.data.data_preprocess import get_masterdata
from src.data.analysis import Top3Analyser
from src.data.features_engineering import filtered_year, filter_last_n_years, top3_percent_last3years, avg_position_last3years

In [4]:
masterdata = get_masterdata()

 Merge step 1: on raceId → shape: (26759, 35)
 Merge step 2: on driverId → shape: (26759, 43)
 Merge step 3: on constructorId → shape: (26759, 47)
 Merge step 4: on ['raceId', 'driverId'] → shape: (26759, 54)

In [5]:
data_from_2000 = filtered_year(masterdata, 2000)

### Top 3 (%) in year -1, -2, -3 for drivers and constructors

In [7]:
drivers_top3_last3_years_percentage = top3_percent_last3years(data_from_2000, 'driverRef')
drivers_top3_last3_years_percentage

year                   2022       2023       2024
full_name
Alexander Albon    0.000000   0.000000   0.000000
Carlos Sainz      40.909091  13.636364  39.130435
Charles Leclerc   50.000000  27.272727  54.166667
Daniel Ricciardo   0.000000   0.000000   0.000000
Esteban Ocon       0.000000   4.545455   4.347826
Fernando Alonso    0.000000  36.363636   0.000000
Franco Colapinto        NaN        NaN   0.000000
George Russell    36.363636   9.090909  16.666667
Guanyu Zhou        0.000000   0.000000   0.000000
Jack Doohan             NaN        NaN   0.000000
Kevin Magnussen    0.000000   0.000000   0.000000
Lance Stroll       0.000000   0.000000   0.000000
Lando Norris       4.545455  31.818182  54.166667
Lewis Hamilton    40.909091  27.272727  20.833333
Liam Lawson             NaN   0.000000   0.000000
Logan Sargeant          NaN   0.000000   0.000000
Max Verstappen    77.272727  95.454545  58.333333
Mick Schumacher    0.000000        NaN        NaN
Nicholas Latifi    0.000000        NaN        NaN
Nico Hülkenberg    0.000000   0.000000   0.000000
Nyck de Vries      0.000000   0.000000        NaN
Oliver Bearman          NaN        NaN   0.000000
Oscar Piastri           NaN   9.090909  33.333333
Pierre Gasly       0.000000   4.545455   4.166667
Sebastian Vettel   0.000000        NaN        NaN
Sergio Pérez      50.000000  40.909091  16.666667
Valtteri Bottas    0.000000   0.000000   0.000000
Yuki Tsunoda       0.000000   0.000000   0.000000

In [10]:
constructors_top3_last3_years_percentage = top3_percent_last3years(data_from_2000, 'constructorRef')
constructors_top3_last3_years_percentage

year                   2022       2023       2024
constructor_name
Alfa Romeo         0.000000   0.000000        NaN
AlphaTauri         0.000000   0.000000        NaN
Alpine F1 Team     0.000000   4.545455   4.166667
Aston Martin       0.000000  18.181818   0.000000
Ferrari           45.454545  20.454545  45.833333
Haas F1 Team       0.000000   0.000000   0.000000
McLaren            2.272727  20.454545  43.750000
Mercedes          38.636364  18.181818  18.750000
RB F1 Team              NaN        NaN   0.000000
Red Bull          63.636364  68.181818  37.500000
Sauber                  NaN        NaN   0.000000
Williams           0.000000   0.000000   0.000000

### Average position in year -1, -2, -3 for drivers and constroctors

In [9]:
drivers_avg_position = avg_position_last3years(data_from_2000, 'driverRef')
drivers_avg_position

year                   2022       2023       2024
full_name
Alexander Albon   12.764706  11.111111  12.705882
Carlos Sainz       3.500000   6.300000   4.714286
Charles Leclerc    3.315789   4.882353   3.913043
Daniel Ricciardo  11.631579  12.714286  12.750000
Esteban Ocon       8.200000   9.312500  13.238095
Fernando Alonso    8.647059   5.600000   9.826087
Franco Colapinto        NaN        NaN  11.166667
George Russell     4.380952   6.631579   5.590909
Guanyu Zhou       12.882353  13.421053  15.227273
Jack Doohan             NaN        NaN  15.000000
Kevin Magnussen   13.166667  14.888889  13.047619
Lance Stroll      11.450000   9.333333  12.619048
Lando Norris       7.800000   7.428571   4.291667
Lewis Hamilton     5.380952   4.900000   5.863636
Liam Lawson             NaN  12.200000  13.500000
Logan Sargeant          NaN  15.000000  16.666667
Max Verstappen     2.809524   1.272727   2.956522
Mick Schumacher   13.631579        NaN        NaN
Nicholas Latifi   15.777778        NaN        NaN
Nico Hülkenberg   14.500000  14.285714  10.666667
Nyck de Vries      9.000000  15.444444        NaN
Oliver Bearman          NaN        NaN   9.666667
Oscar Piastri           NaN   9.631579   5.125000
Pierre Gasly      11.578947  10.238095  11.450000
Sebastian Vettel  10.555556        NaN        NaN
Sergio Pérez       3.950000   4.500000   7.900000
Valtteri Bottas   10.411765  13.368421  15.545455
Yuki Tsunoda      13.062500  12.550000  11.850000

In [11]:
constructors_avg_position = avg_position_last3years(data_from_2000, 'constructorRef')
constructors_avg_position

year                   2022       2023       2024
constructor_name
Alfa Romeo        11.647059  13.394737        NaN
AlphaTauri        12.257143  13.170732        NaN
Alpine F1 Team     8.405405   9.837838  12.428571
Aston Martin      11.200000   7.368421  11.159091
Ferrari            3.400000   5.648649   4.355556
Haas F1 Team      13.405405  14.564103  11.818182
McLaren            9.666667   8.475000   4.708333
Mercedes           4.880952   5.743590   5.727273
RB F1 Team              NaN        NaN  12.428571
Red Bull           3.365854   2.809524   5.255814
Sauber                  NaN        NaN  15.386364
Williams          14.166667  13.000000  13.800000